import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, GoogleAuthProvider, signInWithPopup, sendEmailVerification } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyBdY2t5v-oWRx42aE4_eBG9iw7IM9AP0-o',authDomain:'dialogin-d781e.firebaseapp.com',projectId:'dialogin-d781e',storageBucket:'dialogin-d781e.firebasestorage.app',messagingSenderId:'279545325631',appId:'1:279545325631:web:0dfb9ff70990a663edb08a',measurementId:'G-F56PC9FW28'};
const auth=getAuth(initializeApp(firebaseConfig));const provider=new GoogleAuthProvider();
const goAfterAuth=async user=>{const previousEmail=localStorage.getItem('userEmail')||'';let profile=null;try{profile=JSON.parse(localStorage.getItem('userProfile')||'null')}catch{}const hasProfile=!!profile&&(profile.email===user.email||(!profile.email&&previousEmail===user.email));localStorage.setItem('userEmail',user.email||'');if(hasProfile&&!profile.email){profile.email=user.email;localStorage.setItem('userProfile',JSON.stringify(profile));}window.location.href=hasProfile?'dashboard.html':'About.html';};
const signup=document.getElementById('btn1');if(signup)signup.addEventListener('click',async e=>{e.preventDefault();const email=document.getElementById('SignUpEmail').value.trim(),password=document.getElementById('SPassword').value;if(!email||!password){alert('Please enter your email and password.');return;}if(password.length<6){alert('Password must be at least 6 characters.');return;}signup.disabled=true;try{const {user}=await createUserWithEmailAndPassword(auth,email,password);sendEmailVerification(user).catch(()=>{});await goAfterAuth(user);}catch(error){alert(error.code==='auth/email-already-in-use'?'An account with this email already exists. Please log in.':error.code==='auth/invalid-email'?'Please enter a valid email address.':error.code==='auth/weak-password'?'Password must be at least 6 characters.':error.message);signup.disabled=false;}});
const login=document.getElementById('btn2');if(login)login.addEventListener('click',async e=>{e.preventDefault();const email=document.getElementById('LogInEmail').value.trim(),password=document.getElementById('LPassword').value;if(!email||!password){alert('Please enter your email and password.');return;}login.disabled=true;try{const {user}=await signInWithEmailAndPassword(auth,email,password);if(!user.emailVerified){alert('Please verify your email before logging in.');await auth.signOut();login.disabled=false;return;}await goAfterAuth(user);}catch(error){alert(error.message);login.disabled=false;}});
for(const button of document.querySelectorAll('#googleBtn'))button.addEventListener('click',async()=>{try{const {user}=await signInWithPopup(auth,provider);await goAfterAuth(user);}catch(error){alert(error.message);}});
