document.addEventListener('DOMContentLoaded',()=>{
  const $=id=>document.getElementById(id);const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));const profile=JSON.parse(localStorage.getItem('userProfile')||'null')||{};const initials=(profile.name||'U').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();$('userInitials').textContent=initials;$('topInitials').textContent=initials;$('sidebarName').textContent=profile.name||'Your account';$('currentDate').textContent=new Date().toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});
  const active=m=>m.status!=='archived'&&m.status!=='inactive';const timesOf=m=>(Array.isArray(m.times)&&m.times.length?m.times:[m.time]).filter(Boolean);const formatTimes=m=>timesOf(m).map(t=>new Date(`2000-01-01T${t}`).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})).join(', ')||'No dose times saved';
  function cell(row,text){const el=document.createElement('td');el.textContent=text;row.append(el);return el;}
  function render(){const meds=read('medications');const current=meds.filter(active);const old=meds.filter(m=>!active(m));$('activeCount').textContent=`${current.length} active`;$('historyCount').textContent=`${old.length} ${old.length===1?'record':'records'}`;const body=$('activeMedicines');body.replaceChildren();$('activeEmpty').hidden=!!current.length;
    current.forEach(m=>{const tr=document.createElement('tr');const name=cell(tr,m.name||'Medicine');name.className='medicine-name';cell(tr,m.dosage||'Not set');cell(tr,`${m.frequency||`${timesOf(m).length||1} time(s) daily`} · ${formatTimes(m)}`);cell(tr,m.mealTiming||m.notes||'Not specified');const action=cell(tr,'');const btn=document.createElement('button');btn.className='table-action';btn.textContent='Move to history';btn.addEventListener('click',()=>changeStatus(m.id,'archived'));action.append(btn);body.append(tr);});
    const hist=$('medicineHistory');hist.replaceChildren();$('historyEmpty').hidden=!!old.length;old.slice().reverse().forEach(m=>{const tr=document.createElement('tr');const name=cell(tr,m.name||'Medicine');name.className='medicine-name';cell(tr,m.dosage||'Not set');cell(tr,`${m.frequency||''} ${formatTimes(m)}`.trim());cell(tr,m.addedAt?new Date(m.addedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—');const action=cell(tr,'');const btn=document.createElement('button');btn.className='table-action restore-action';btn.textContent='Reactivate';btn.addEventListener('click',()=>changeStatus(m.id,'active'));action.append(btn);hist.append(tr);});
  }
  function changeStatus(id,status){const meds=read('medications');const item=meds.find(m=>String(m.id)===String(id));if(item){item.status=status;item.updatedAt=new Date().toISOString();write('medications',meds);render();}}
  function open(){ $('medicationModal').showModal(); }
  $('openMedication').addEventListener('click',open);$('emptyAddMedication').addEventListener('click',open);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
  $('medFrequency').addEventListener('change',()=>{const n=Number($('medFrequency').value);$('doseTime2Wrap').hidden=n<2;$('doseTime3Wrap').hidden=n<3;$('medTime2').required=n>=2;$('medTime3').required=n>=3;});
  $('medicationForm').addEventListener('submit',e=>{e.preventDefault();const name=$('medName').value.trim(),dosage=$('medDosage').value.trim(),n=Number($('medFrequency').value),times=[$('medTime1').value,$('medTime2').value,$('medTime3').value].slice(0,n);if(!name||!dosage||times.some(t=>!t))return;const meds=read('medications');meds.push({id:Date.now(),name,dosage,time:times[0],times,frequency:`${n} time${n===1?'':'s'} daily`,mealTiming:$('medMeal').value,status:'active',addedAt:new Date().toISOString()});write('medications',meds);$('medicationForm').reset();$('doseTime2Wrap').hidden=true;$('doseTime3Wrap').hidden=true;$('medTime2').required=false;$('medTime3').required=false;$('medicationModal').close();render();});
  render();
});
